controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
pdf_generate:
    path: '/generate-pdf'
    controller: 'App\Controller\ChevaletController::generatePdf'
    methods: ['POST']

